#!/bin/sh
echo acq400_common.init
get_u-boot_env
mkdir -p /etc/acq400/
mount -t ramfs ram /etc/acq400
mkdir /etc/acq400/0
ln -s /usr/local/bin/soft_trigger /etc/acq400/0/soft_trigger
# may need to do this again later if more services are defined
make-console-links

patch_check() {
	/mnt/bin/check_version >/dev/null
	if [ $? ]; then
		echo PATCHED
	else
		echo CLEAN
	fi
}
	
echo $(head -n 1 /mnt/version | awk '{ print $2 }') $(patch_check) >/tmp/version

