#!/bin/sh

if [ -e /dev/mtd0 ]; then
	dd if=/dev/mtd0 bs=1024 skip=896 | dump-cstrings | 
		grep -v \&\& | sed -e 's/=/="/' -e 's/$/"/' >/tmp/u-boot_env
else
	echo "# dummy env" > /tmp/u-boot_env
fi



