#!/bin/sh

log() {
/usr/bin/logger -t fix-leds $*
}

if [ "x$FIX_LEDS_SLEEP" != "x" ]; then
	sleep $FIX_LEDS_SLEEP
fi
log 01
cd /dev/gpio/LED
for led in *; do
    state=$(cat $led)
    if [ "$state" = "-22" ]; then
        log $led $state fix 0
	state=0
    fi
    echo $state > $led
done

log 99



