#!/bin/sh

irate() {
	echo $(/usr/local/CARE/int_rate_mon xuartps 5 1 | head -n 1 | awk '{ print $3 }')
}
IRATE=$(irate)

KILLSWITCH=/sys/module/xilinx_uartps/parameters/kill_switch_mask

slug_it() {

if [  $IRATE -gt 1000 ]; then
	echo SLUG suspected line noise on /dev/ttyPS0 $IRATE
	if [ -e $KILLSWITCH ]; then
		echo SLUG activate KILLSWITCH
		echo 65535,0 > $KILLSWITCH
		sleep 1
		IRATE=$(irate)
	else
		echo SLUG : no KILLSWITCH
	fi
	if [ $IRATE -lt 10 ]; then
		echo SLUG suspected line noise on /dev/ttyPS0 $IRATE SUCCESS
	else
		echo SLUG suspected line noise on /dev/ttyPS0 $IRATE FAIL
	fi
else
	echo SLUG ttyPS0 interrupts normal NO ACTION	
fi
}


if [ "x$1" = "xdaemon" ]; then
	shift;
	SLEEP=${1:-60}
	slug_it | /usr/bin/logger -t slug
else
	slug_it
fi
