#!/bin/sh

irate() {
	echo $(/usr/local/CARE/int_rate_mon xuartps 5 1 | head -n 1 | awk '{ print $3 }')
}
IRATE=$(irate)

slug_it() {
if [  $IRATE -gt 1000 ]; then
	echo SLUG suspected line noise on /dev/ttyPS0 $IRATE
	sed -ie '/console/a::shutdown:/bin/stty -F /dev/ttyPS0 speed 115200' /etc/inittab
	sed -ie 's/^console::/#console::/' /etc/inittab
	kill -HUP 1
	sleep 1
	pkill -9 getty
	stty -F /dev/ttyPS0 speed 50 >/dev/null
	IRATE=$(irate)
	if [ $IRATE -lt 10 ]; then
		echo SLUG suspected line noise on /dev/ttyPS0 $IRATE SUCCESS
	else
		echo SLUG suspected line noise on /dev/ttyPS0 $IRATE FAIL
	fi
else
	echo SLUG ttyPS0 interrupts normal NO ACTION	
fi
}


if [ "x$1" = "xdaemon" ]; then
	shift;
	SLEEP=${1:-60}
	slug_it | /usr/bin/logger -t slug
else
	slug_it
fi
