#!/bin/sh

link_ready=0

if [ "x$1" != "x" ]; then
	echo +++ starting rsyslog $1

	(	
	while [ $link_ready -eq 0 ]; do
		for k in /sys/class/net/eth?/operstate; do
			state=$(cat $k)
			if [ "$state" = "up" ]; then
				link_ready=1
				break
			fi
		done
		sleep 1
	done

	ping_fail=1
	retry=0
	while [ $ping_fail -ne 0 ]; do
	    retry=$(($retry+1))
	    if [ $retry -gt 10 ]; then
	    	echo +++ ERROR rsyslog ping $1 fail retry $retry quit
	    	exit 1
	    fi
		timeout 2 ping -c 1 $1
		ping_fail=$?
		[ $ping_fail -eq 0 ] || sleep 2
	done
	
	killall syslogd
	syslogd -R $1:514
	klogd -c 1
	logger -t acq400common rsyslog started ..
	) &
fi
